### PR TITLE
[SAYP-556] Add set metadata feature

### PR DESCRIPTION
**Pull request by maoertel**
This PR adds a feature to set Metadata of a Secret. Unfortunately `vaultrs` does not handle setting of custom metadata, somehow, so we call the API directly.

### CODE REVIEW

**Comment by maoertel** [comment]
Successful test run in vw staging

**Review by adrobisch — APPROVED** [review]
I guess we could also have a helper method that does both at the same time (optional metadata arg) including handling the version?

**Comment by maoertel** [comment]
> I guess we could also have a helper method that does both at the same time (optional metadata arg) including handling the version?

Sure.

**Comment by maoertel** [comment]
> > I guess we could also have a helper method that does both at the same time (optional metadata arg) including handling the version?
> 
> Sure.

Maybe we should stop with the extended feature'ism at some point. 🤔 As it grows bigger that adds accidental complexity somehow.

**Pull request merged**
